# fly.toml app configuration file generated for mai-num on 2025-03-20T20:43:41-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mai-num'
primary_region = 'gig'

[build]


[http_service]
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

